export const ICONS = {
  agua: "/Icons/agua.png",
  almoco_adulto: "/Icons/almocoadulto.png",
  almoco_socio: "/Icons/almocosocio.png",
  barril: "/Icons/barril.png",
  caipirinha: "/Icons/caipirinha.png",
  cer_garrafa: "/Icons/cerveja-garrafa.png",
  cer_lata: "/Icons/cerveja-lata.png",
  chope: "/Icons/chope.png",
  fichas: "/Icons/fichas.png",
  lanche: "/Icons/lanche.png",
  meio_almoco: "/Icons/meioalmoco.png",
  petchopp: "/Icons/petchopp.png",
  petchopp_2l: "/Icons/petchopp2l.png",
  picole: "/Icons/picole.png",
  prato_talher: "/Icons/pratotalher.png",
  ref_1l: "/Icons/refri-1l.png",
  ref_2l: "/Icons/refri-2l.png",
  ref_600: "/Icons/refri-600.png",
  ref_lata: "/Icons/refri-lata.png",
  sobremesa: "/Icons/sobremesa.png",
  sorvete: "/Icons/sorvete.png",
  suco: "/Icons/suco.png",
};
