export const PRODUCT_SHORTCUTS = [
  { key: "agua", nome: "Água", imagem: "agua.png" },
  { key: "almoco_adulto", nome: "Almoço Adulto", imagem: "almocoadulto.png" },
  { key: "almoco_socio", nome: "Almoço Sócio", imagem: "almocosocio.png" },
  { key: "barril", nome: "Barril de chopp", imagem: "barril.png" },
  { key: "caipirinha", nome: "Caipirinha", imagem: "caipirinha.png" },
  { key: "cer_garrafa", nome: "Cerveja Garrafa", imagem: "cerveja-garrafa.png" },
  { key: "cer_lata", nome: "Cerveja Lata", imagem: "cerveja-lata.png" },
  { key: "chope", nome: "Chope", imagem: "chope.png" },
  { key: "fichas", nome: "Fichas de almoço", imagem: "fichas.png" },
  { key: "lanche", nome: "Lanche", imagem: "lanche.png" },
  { key: "meio_almoco", nome: "Meio almoço", imagem: "meioalmoco.png" },
  { key: "pet_chopp", nome: "Pet chopp", imagem: "petchopp.png" },
  { key: "picole", nome: "Picolé", imagem: "picole.png" },
  { key: "prato_talher", nome: "Prato e talher", imagem: "pratotalher.png" },
  { key: "ref_1l", nome: "Refrigerante 1L", imagem: "refri-1l.png" },
  { key: "ref_2l", nome: "Refrigerante 2L", imagem: "refri-2l.png" },
  { key: "ref_600", nome: "Refrigerante 600ml", imagem: "refri-600.png" },
  { key: "ref_lata", nome: "Refrigerante lata", imagem: "refri-lata.png" },
  { key: "sobremesa", nome: "Sobremesa", imagem: "sobremesa.png" },
  { key: "sorvete", nome: "Sorvete", imagem: "sorvete.png" },
  { key: "suco", nome: "Suco", imagem: "suco.png" },
];
